{{- if or .Values.rbac.clusterWide .Values.rbac.readNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: seldon-deploy-role
rules:
  {{- if .Values.rbac.readNamespaces }}
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  {{- end }}
  {{- if .Values.rbac.clusterWide }}
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - 'apiextensions.k8s.io'
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments/finalizers
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mlops.seldon.io
    resources:
      - pipelines
      - models
      - experiments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch  
  - apiGroups:
      - mlops.seldon.io
    resources:
      - pipelines/finalizers
      - models/finalizers
      - experiments/finalizers
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mlops.seldon.io
    resources:
      - pipelines/status
      - models/status
      - experiments/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - networking.istio.io
    resources:
      - destinationrules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - destinationrules/status
    verbs:
      - get
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices/status
    verbs:
      - get
  - apiGroups:
      - security.istio.io
    resources: 
      - authorizationpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - v1
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - v1
    resources:
      - services/status
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
      - update
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - eventing.knative.dev
    resources:
      - triggers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - eventing.knative.dev
    resources:
      - brokers
    verbs:
      - get
  {{- end }}
{{- end }}
