{{- $namespaces := .Values.rbac.namespaces -}}
{{- $namespaces = append $namespaces .Release.Namespace -}}

{{- if .Values.rbac.create }}
{{- range $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seldon-deploy-rolebinding
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seldon-deploy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "seldon-deploy.serviceAccountName" $ }}
    namespace: '{{ $.Release.Namespace }}'
{{- end }}
{{- end }}
