# Note: not currently used, may be useful later.
{{- if .Values.ui -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seldon-deploy.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "seldon-deploy.name" . }}
    helm.sh/chart: {{ include "seldon-deploy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ toYaml . }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "seldon-deploy.name" . }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}